[raw]
date              = 'datetime64'
winner            = 'string'
loser             = 'string'
wrank             = 'int64'
lrank             = 'int64'
b365w             = 'float64'
b365l             = 'float64'
surface           = 'string'

[features]
rank_p1                 = 'int64'
rank_p2                 = 'int64'
rank_diff               = 'int64'
rank_ratio              = 'float64'
odd_p1                  = 'float64'
odd_p2                  = 'float64'
odd_diff                = 'float64'
odd_ratio               = 'float64'
surface_Clay            = 'int64'
surface_Hard            = 'int64'
surface_Grass           = 'int64'
h2h                     = 'int64'
consecutive_wins_p1     = 'int64' 
consecutive_wins_p2     = 'int64'
consecutive_losses_p1   = 'int64'
consecutive_losses_p2   = 'int64'
consecutive_results     = 'int64'
rank_evol_p1            = 'int64'
rank_evol_p2            = 'int64'
record_p1               = 'int64'
record_p2               = 'int64'
