[env]
APP_NAME = 'tennis-predictor'
APP_VERSION = 'v1'
API_PREFIX = '/api/v1'
DEBUG = 1

[app]
raw_data_path = 'app/data/raw/'
interim_data_path = 'app/data/interim/'
processed_data_path = 'app/data/processed/'
